# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: StreamCardano project
email: migamake@migamake.com
description: > # this means to ignore newlines until "baseurl:"
  StreamCardano project home page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://streamcardano.gitlab.io" # the base hostname & protocol for your site
logo: "/images/logo.png"
twitter_username: migamake
github_username:  migamake
gitlab_username:  migamake
google_analytics: 

# Outputting
permalink: /:categories/:year/:month/:day/:title

collections:
  posts:
    output: true
    permalink: /news/:path/
  demos:
    output: true
    permalink: /demos/:path/
  docs:
    output: true
    permalink: /docs/:path/
  partners:
    output: true
    permalink: /partners/:path/
  downloads:
    output: true
    permalink: /downloads/:path/

# Build settings
# encoding: utf-8
markdown: kramdown
exclude: ["README.md", "vendor"]
plugins:
  - jekyll-sitemap
  - jekyll-image-size
  - jekyll-resize
  # - jekyll-image-optim
  # - jekyll-responsive_image

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/rss.xml"
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# theme: alembic-jekyll-theme


# Site navigation
navigation:
- title: News
  url: /news/
  icon: ico-news
- title: Demos
  url: /demos/
  icon: ico-exm
- title: Partners
  url: /partners/
  icon: ico-news
- title: Docs
  url: https://streamcardano.readme.io
  icon: ico-doc
- title: App
  url: /in-progress
  icon: ico-exm
  # url: https://app.streamcardano.com
- title: login
  url: "/in-progress"
  btnClass: btn-brdr
- title: Signup
  url: "/in-progress"
  btnClass: btn-fill

# footer link/id
catalyst: https://cardano.ideascale.com/a/community/login
discord_channel: https://discord.gg/VRcs553q
keybase_channel: https://keybase.io/team/migamakeusers
telegram_channel: https://t.me/migamake
