# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: StreamCardano project
email: migamake@migamake.com
description: > # this means to ignore newlines until "baseurl:"
  StreamCardano project home page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://streamcardano.github.io" # the base hostname & protocol for your site
twitter_username: migamake
github_username:  migamake
gitlab_username:  migamake

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]

theme: alembic-jekyll-theme
