# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
logo: "/assets/images/searchain-logo.jpg"
title: StreamCardano project
email: migamake@migamake.com
description: > # this means to ignore newlines until "baseurl:"
  StreamCardano project home page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://streamcardano.github.io" # the base hostname & protocol for your site
twitter_username: migamake
github_username:  migamake
gitlab_username:  migamake
repository:       streamcardano/streamcardano.github.io

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude:
  - "README.md"
  - "vendor"

plugins:
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-spaceship
  - jekyll-responsive-image
  - jekyll-seo-tags
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
remote_theme: pages-themes/hacker@v0.2.0
#remote_theme:  Wiredcraft/carte
#remote_theme: just-the-docs/just-the-docs
#remote_theme: tomjoht/documentation-theme-jekyll
#remote_theme: karloespiritu/BlackDoc

jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - element-processor
html_proofer:
  check_favicon: true
  check_html: true
  file_ignore:
    - /a.*regexp*/
    - a_string
# links to channels
discord: https://discord.gg/VRcs553q
keybase: https://keybase.io/team/migamakeusers
telegram: https://t.me/migamake7

# Collections
collections:
  demo:
    output: true
    permalink: /demo/:path/


